const MANUAL_FALLBACKS = {
    "Thiruvananthapuram": [
        { name: "RDR Convention Centre", address: "Edapazhinji, Thiruvananthapuram", location: { lat: 8.50358, lng: 76.9681 } },
        { name: "Al Saj Convention Centre", address: "Kazhakkoottam, Thiruvananthapuram", location: { lat: 8.575396, lng: 76.869806 } },
        { name: "Girideepam Convention Centre", address: "Nalanchira, Thiruvananthapuram", location: { lat: 8.55146, lng: 76.93918 } },
        { name: "Udaya Samudra Leisure Beach Hotel", address: "Kovalam, Thiruvananthapuram", location: { lat: 8.3986, lng: 76.9806 } },
        { name: "Hycinth Hotels", address: "Manorama Road, Thiruvananthapuram", location: { lat: 8.4975, lng: 76.9535 } },
        { name: "Apollo Dimora", address: "Thampanoor, Thiruvananthapuram", location: { lat: 8.4913, lng: 76.9525 } },
        { name: "Classic Avenue", address: "Manjalikulam Road, Thiruvananthapuram", location: { lat: 8.4935, lng: 76.9490 } },
        { name: "B-Hub", address: "Mar Ivanios Vidya Nagar, Thiruvananthapuram", location: { lat: 8.5456, lng: 76.9385 } },
        { name: "Travancore International Convention Centre", address: "Karyavattom, Thiruvananthapuram", location: { lat: 8.5635, lng: 76.8835 } },
        { name: "St. Joseph's Auditorium", address: "Palayam, Thiruvananthapuram", location: { lat: 8.5050, lng: 76.9550 } },
        { name: "Vylopilly Samskrithi Bhavan", address: "Nalanda, Thiruvananthapuram", location: { lat: 8.5135, lng: 76.9545 } },
        { name: "Priyadarshini Hall", address: "East Fort, Thiruvananthapuram", location: { lat: 8.4830, lng: 76.9450 } },
        { name: "Hassan Marakar Hall", address: "Palayam, Thiruvananthapuram", location: { lat: 8.5045, lng: 76.9540 } },
        { name: "Karthika Thirunal Theatre", address: "East Fort, Thiruvananthapuram", location: { lat: 8.4825, lng: 76.9455 } },
        { name: "Tagore Theatre", address: "Vazhuthacaud, Thiruvananthapuram", location: { lat: 8.4985, lng: 76.9575 } },
        { name: "Jimmy George Indoor Stadium", address: "Vellayambalam, Thiruvananthapuram", location: { lat: 8.5085, lng: 76.9620 } }
    ],
    "Alappuzha": [
        { name: "Camelot Convention Centre", address: "Pathirappally, Alappuzha" },
        { name: "Bhuvi Convention Center", address: "Nangyarkulangara, Alappuzha" },
        { name: "Grace Convention Centre", address: "Mavelikara, Alappuzha" },
        { name: "Alleppey Prince Hotel", address: "AS Road, Alappuzha" },
        { name: "Ramada by Wyndham", address: "Nehru Trophy Boat Race Finishing Point, Alappuzha" },
        { name: "Raheem Residency", address: "Beach Road, Alappuzha" },
        { name: "Lake Palace Resort", address: "Thirumala Ward, Alappuzha" },
        { name: "Pagoda Resort", address: "Chungham, Alappuzha" },
        { name: "Contour Backwaters", address: "Changanassery, Alappuzha" },
        { name: "KGA Elite Continental", address: "Thiruvalla, Alappuzha" }
    ],
    "Ernakulam": [
        { name: "Lulu Bolgatty International Convention Center", address: "Mulavukad, Kochi" },
        { name: "Adlux International Convention & Exhibition Centre", address: "Angamaly, Ernakulam" },
        { name: "Cial Convention Centre", address: "Nedumbassery, Ernakulam" },
        { name: "Gokulam Park", address: "Kaloor, Kochi" },
        { name: "Rena Event Hub", address: "Kaloor, Kochi" },
        { name: "Udyan Convention Centre", address: "Vennala, Kochi" },
        { name: "Samudrika Hall", address: "Willingdon Island, Kochi" },
        { name: "Le Meridien Kochi", address: "Maradu, Kochi" },
        { name: "Crowne Plaza Kochi", address: "Kundannoor, Kochi" },
        { name: "Grand Hyatt Kochi Bolgatty", address: "Bolgatty Island, Kochi" },
        { name: "Dream Hotel", address: "Kadavanthra, Kochi" },
        { name: "Holiday Inn Cochin", address: "Vennala, Kochi" },
        { name: "Olive Downtown", address: "Kadavanthra, Kochi" },
        { name: "Presidency Hotel", address: "Paramara Road, Kochi" },
        { name: "The Avenue Regent", address: "MG Road, Kochi" }
    ],
    "Idukki": [
        { name: "Hirange Residency", address: "Thodupuzha, Idukki" },
        { name: "Merryget", address: "Thodupuzha, Idukki" },
        { name: "Green Berg Resort", address: "Kulamavu, Idukki" },
        { name: "Carmelia Haven", address: "Vandanmedu, Idukki" },
        { name: "Mountain Club Resort", address: "Chinnakanal, Idukki" },
        { name: "Silver Tips", address: "Munnar, Idukki" },
        { name: "Tea County", address: "Munnar, Idukki" },
        { name: "Club Mahindra", address: "Munnar, Idukki" },
        { name: "Sterling Munnar", address: "Chinnakanal, Idukki" },
        { name: "Blanket Hotel & Spa", address: "Pallivasal, Idukki" }
    ],
    "Kannur": [
        { name: "Sreevalsam Auditorium", address: "Payyanur, Kannur" },
        { name: "Babil Greens Convention Centre", address: "Taliparamba, Kannur" },
        { name: "Dinesh Auditorium", address: "Kannur" },
        { name: "Dream Palace Auditorium", address: "Taliparamba, Kannur" },
        { name: "Luxotica International Convention Centre", address: "Kannur" },
        { name: "Riftha Hall", address: "Kannur" },
        { name: "Green Park Auditorium", address: "Kannur" },
        { name: "Sadhoo Kalyana Mandapam", address: "Kannur" },
        { name: "Parassinikadavu Muthappan Auditorium", address: "Parassinikadavu, Kannur" },
        { name: "Kuku's Nest", address: "Thalassery, Kannur" }
    ],
    "Kasaragod": [
        { name: "Oryx Village", address: "Kanhangad, Kasaragod" },
        { name: "Grand Auditorium", address: "Manjeshwar, Kasaragod" },
        { name: "Malik Deenar Cultural Centre", address: "Thalangara, Kasaragod" },
        { name: "Municipal Town Hall", address: "Kasaragod" },
        { name: "Bekal Palace", address: "Bekal, Kasaragod" },
        { name: "The Lalit Resort & Spa", address: "Bekal, Kasaragod" },
        { name: "Taj Bekal Resort", address: "Bekal, Kasaragod" },
        { name: "Kanhangad Town Hall", address: "Kanhangad, Kasaragod" },
        { name: "Nalanda Auditorium", address: "Nileshwar, Kasaragod" },
        { name: "Soorya Auditorium", address: "Cheruvathur, Kasaragod" }
    ],
    "Kollam": [
        { name: "Grand Highness Convention Centre", address: "Kollam" },
        { name: "Sreedhareeyam Convention Centre", address: "Kollam" },
        { name: "Monaarch Convention Centre", address: "Kollam" },
        { name: "Lalas Convention Centre", address: "Kollam" },
        { name: "The Raviz", address: "Thevally, Kollam" },
        { name: "Quilon Beach Hotel", address: "Beach Road, Kollam" },
        { name: "Nani Hotel", address: "Chinnakada, Kollam" },
        { name: "Hotel Regant Lake Palace", address: "Neendakara, Kollam" },
        { name: "Kadappakada Sports Club Hall", address: "Kadappakada, Kollam" },
        { name: "Sree Narayana Guru Cultural Complex", address: "Kollam" }
    ],
    "Kottayam": [
        { name: "Aithousa Convention Centre", address: "Kumaranalloor, Kottayam" },
        { name: "Windsor Castle Convention Centre", address: "Kottayam" },
        { name: "Mammen Mappilla Hall", address: "Kottayam" },
        { name: "Michaels Plaza", address: "Ramapuram, Kottayam" },
        { name: "Backwater Ripples", address: "Kumarakom, Kottayam" },
        { name: "The Zuri Kumarakom", address: "Kumarakom, Kottayam" },
        { name: "Kumarakom Lake Resort", address: "Kumarakom, Kottayam" },
        { name: "Hotel Arcadia", address: "Kottayam" },
        { name: "Chavara Kuriakose Elias Hall", address: "Mannanam, Kottayam" },
        { name: "Illikkalam Resort Hall", address: "Kumarakom, Kottayam" }
    ],
    "Kozhikode": [
        { name: "Calicut Trade Centre", address: "Sarovaram, Kozhikode" },
        { name: "Tagore Centenary Hall", address: "Kozhikode" },
        { name: "K Hills Heritage", address: "Ramanattukara, Kozhikode" },
        { name: "Lavandis Convention Centre", address: "Eranhikkal, Kozhikode" },
        { name: "Tripenta Hotel", address: "Kozhikode" },
        { name: "The Raviz Kadavu", address: "Azhinjilam, Kozhikode" },
        { name: "Copper Folia", address: "Thondayad, Kozhikode" },
        { name: "Vasco Dagama Beach Resort", address: "Kappad, Kozhikode" },
        { name: "Marina Convention Centre", address: "Kozhikode" },
        { name: "Nalanda Auditorium", address: "Kozhikode" }
    ],
    "Malappuram": [
        { name: "Rose Lounge", address: "Malappuram" },
        { name: "Rio Convention Centre", address: "Anakkayam, Malappuram" },
        { name: "Shifa Convention Center", address: "Perinthalmanna, Malappuram" },
        { name: "Woodbine", address: "Manjeri, Malappuram" },
        { name: "Hotel Rydges Inn", address: "Kottakkal, Malappuram" },
        { name: "Emarald Ayurvedic Resort", address: "Pulamanthole, Malappuram" },
        { name: "Valluvanad Convention Centre", address: "Perinthalmanna, Malappuram" },
        { name: "Mahendra Puri", address: "Kottakkal, Malappuram" },
        { name: "Flora Fantasia Hall", address: "Valanchery, Malappuram" },
        { name: "Grand Auditorium", address: "Tirur, Malappuram" }
    ],
    "Palakkad": [
        { name: "Jobys Mall Convention Centre", address: "Palakkad" },
        { name: "Top in Town Auditorium", address: "Palakkad" },
        { name: "Indraprastha", address: "English Church Road, Palakkad" },
        { name: "Soorya Residency", address: "Robinson Road, Palakkad" },
        { name: "Tripenta Hotel", address: "Malampuzha, Palakkad" },
        { name: "Kairali Heritage", address: "Kattampazhayoor, Palakkad" },
        { name: "Hotel Gazala", address: "Palakkad" },
        { name: "Noor Jehan's Grand", address: "Palakkad" },
        { name: "Sayoojyam Residency", address: "Palakkad" },
        { name: "Rithu Mahal", address: "Ottapalam, Palakkad" }
    ],
    "Pathanamthitta": [
        { name: "Loyal Convention Centre", address: "Thiruvalla, Pathanamthitta" },
        { name: "Balakrishna Convention Centre", address: "Pathanamthitta" },
        { name: "M Convention Centre", address: "Pathanamthitta" },
        { name: "Club 7 Hotel", address: "Thiruvalla, Pathanamthitta" },
        { name: "Hotel Elite Continental", address: "Thiruvalla, Pathanamthitta" },
        { name: "Mannil Regency", address: "Pathanamthitta" },
        { name: "Hey Day Hotel", address: "Pathanamthitta" },
        { name: "Tharangam Auditorium", address: "Ranni, Pathanamthitta" },
        { name: "Konni Town Hall", address: "Konni, Pathanamthitta" },
        { name: "Adoor Town Hall", address: "Adoor, Pathanamthitta" }
    ],
    "Thrissur": [
        { name: "Lulu International Convention Center", address: "Thrissur" },
        { name: "Joys Palace", address: "Thrissur" },
        { name: "Hyatt Regency", address: "Thrissur" },
        { name: "Casino Hotels", address: "Thrissur" },
        { name: "Trichur Towers", address: "Thrissur" },
        { name: "Dass Continental", address: "Thrissur" },
        { name: "Kousthubham Auditorium", address: "Guruvayoor, Thrissur" },
        { name: "Rugmini Regency", address: "Guruvayoor, Thrissur" },
        { name: "Sree Krishna Hall", address: "Guruvayoor, Thrissur" },
        { name: "Elite International", address: "Thrissur" }
    ],
    "Wayanad": [
        { name: "Vythiri Village Resort", address: "Vythiri, Wayanad" },
        { name: "The Windflower Resort & Spa", address: "Vythiri, Wayanad" },
        { name: "Upavan Resort", address: "Lakkidi, Wayanad" },
        { name: "Green Gates Hotel", address: "Kalpetta, Wayanad" },
        { name: "Wayanad Silver Woods", address: "Kalpetta, Wayanad" },
        { name: "Banasura Hill Resort", address: "Vellamunda, Wayanad" },
        { name: "Sharoy Resort", address: "Banasura Sagar, Wayanad" },
        { name: "Vythiri Holiday Resort", address: "Vythiri, Wayanad" },
        { name: "Raindrops Resort", address: "Sultan Bathery, Wayanad" },
        { name: "Le Villagio Holiday Apartments", address: "Sultan Bathery, Wayanad" }
    ]
};

module.exports = MANUAL_FALLBACKS;
